### ISSUE TITLE
版本号是不是没用处理好。

### ISSUE THREAD

**Issue by jalena** [FuckDoctors/rdm-builder#12]
下载的rdm-2021.5.0.exe安装后显示版本为2021.3.0-dev

![image](https://user-images.githubusercontent.com/5668673/122171905-d223e380-ceb2-11eb-9b16-402cb1465465.png)

**Comment by FuckDoctors** [comment]
pre-release的修改了，正式版的下次再改

**Comment by jalena** [comment]
mac版本的2021.5显示的还是2021.3.0-Dev

**Comment by FuckDoctors** [comment]
2021.6已修复

**Comment by jalena** [comment]
> 2021.6已修复

完美。感谢
