### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by Lvbuqing** [FuckDoctors/rdm-builder#14]
有几个问题想咨询一下：
1.代码是每晚从官方地址拉去的吗？
2.代码拉取打包修改了哪些地方？
3.安装发现没有原版的登录授权界面，是去掉了这一块的代码吗？

**Comment by FuckDoctors** [comment]
1. pre-release是每晚拉取官方代码
2. 本repo只做打包，不做代码修改
3. 没做代码修改，官方repo是开源版本，所以没有授权页面

**Comment by Lvbuqing** [comment]
多谢大佬，支持！
