### ISSUE TITLE
Why can't I check the cache time or expiration time?

### ISSUE THREAD

**Issue by 759852125** [FuckDoctors/rdm-builder#20]
Why can't I check the cache time or expiration time?

**Comment by FuckDoctors** [comment]
Do you mean `TTL`?
You can use command `ttl key` to check the expiration time.
Or, checking the `TTL` button in the UI.
![image](https://user-images.githubusercontent.com/1180450/147237391-8d7f58e2-af73-46ff-a9f9-18576b01bc1e.png)
