### ISSUE TITLE
Python: mach-o, but wrong architecture

### ISSUE THREAD

**Issue by cuongngoz** [FuckDoctors/rdm-builder#22]
I tried open RESP app on macbook M1 Apple chip, geting this issue
```
Dyld Error Message:
  Library not loaded: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python
  Referenced from: /Applications/RESP.app/Contents/MacOS/RESP
  Reason: no suitable image found.  Did find:
	/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python: mach-o, but wrong architecture
	/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/Python: mach-o, but wrong architecture
```

**Comment by FuckDoctors** [comment]
FYI, check this post:
[TIP | The BEST way to install Homebrew (Brew) on Apple Silicon (M1)
](https://wnderlvst.com/stories/5101f1ca-a1c8-4dfc-b469-ccf4dae0d823)

From: https://github.com/alibaba/nacos/issues/4336#issuecomment-821246302

**Comment by geekscloud** [comment]
我也遇到的相同的问题, 最新的几个版本都不行

**Comment by lemos1235** [comment]
不行，架构不支持。pyhton3.9 已经软链接了

<img width="946" alt="image" src="https://user-images.githubusercontent.com/23135552/184442351-f88cdaad-86bd-401c-972e-9b03f2dc7d8d.png">

**Comment by lemos1235** [comment]
架构不兼容，提示不是 x86_64

<img width="879" alt="image" src="https://user-images.githubusercontent.com/23135552/184442648-8b4c8c11-7b33-40d2-ad11-2c14c9040fdc.png">

**Comment by FuckDoctors** [comment]
> 架构不兼容，提示不是 x86_64
> 
> <img alt="image" width="879" src="https://user-images.githubusercontent.com/23135552/184442648-8b4c8c11-7b33-40d2-ad11-2c14c9040fdc.png">

按照这个，安装一个别的版本的homebrew，然后用这个版本的homebrew安装python。
https://github.com/FuckDoctors/rdm-builder/issues/22#issuecomment-1096150738
