### ISSUE TITLE
v2022.3 没有版本号

### ISSUE THREAD

**Issue by jpacg** [FuckDoctors/rdm-builder#25]
`App Store` 一直显示 `RESP.app` 的更新，检查了下发现里面没有版本号

**Comment by FuckDoctors** [comment]
App Store版是原作者发布的收费版
这个是自编译版本
没有购买原作者的收费版，不清楚他的版本号。

**Comment by jpacg** [comment]
@FuckDoctors 谢谢啊，是我自己记错，之前 `App Store` 没显示，我误以为有版本号。
