### ISSUE TITLE
2022.4.2 支持 MsgPack 吗？

### ISSUE THREAD

**Issue by jacksonwj** [FuckDoctors/rdm-builder#27]
安装好 2022.4.2 之后，没法显示 MsgPack 序列化/反序列化，但是看到官方说是支持的。需要本地怎么配置吗？

**Comment by FuckDoctors** [comment]
貌似是可以支持的，安装依赖的时候应该已经安装了：
https://github.com/uglide/RedisDesktopManager/blob/1098ff66ae3653880db0c8e069f209626776ccad/src/py/requirements.txt#L3
本地的python版本对的话，应该不需要额外配置。

好久不用redis了，如果发现编译有问题，欢迎PR~

**Comment by FuckDoctors** [comment]
编译log:
https://github.com/FuckDoctors/rdm-builder/runs/7561070348?check_suite_focus=true#step:10:91

**Comment by jacksonwj** [comment]
@FuckDoctors 

反复试了几次，其它配置都没变，只是卸载了 2022.2，全新安装 2022.4.2，还是没办法显示出来，不知道是怎么回事。

实在不行，要么退回 2022.2，要么，自己写一个 msgpack extention server。

这是 2022.2 的截图

![2022.2](https://user-images.githubusercontent.com/61455/183577829-bf64a998-e093-4582-b0ba-f97938329166.png)

这是 2022.4.2 的截图

![2022.4.2](https://user-images.githubusercontent.com/61455/183577900-eca0a095-fbbf-4b73-bbaf-8058063803b6.png)
