### ISSUE TITLE
2022.5 release 现在需要 brew install python@3.10

### ISSUE THREAD

**Issue by gafffey** [FuckDoctors/rdm-builder#28]

**Comment by wuhan321** [comment]
我也安装了python@3.10,,,还是打不开,请教下怎么回事

**Comment by FuckDoctors** [comment]
> 我也安装了python@3.10,,,还是打不开,请教下怎么回事

正式版用的python 3.10，Nightly用的3.11.
Win用的3.9.

**Comment by wuhan321** [comment]
安装了python3.11,下载了 Nightly版本,还是无法打开,,隐私设置里点击的仍然打开弹两下就没有了反应,,,,  是python安装的不对吗? 控制台输入了python没有提示,输入python3.11就可以进入python环境,,,是这个原因吗?

**Comment by wuhan321** [comment]
> > 我也安装了python@3.10,,,还是打不开,请教下怎么回事
> 
> 正式版用的python 3.10，Nightly用的3.11. Win用的3.9.

安装了python3.11,下载了 Nightly版本,还是无法打开,,隐私设置里点击的仍然打开弹两下就没有了反应,,,, 是python安装的不对吗? 控制台输入了python没有提示,输入python3.11就可以进入python环境,,,是这个原因吗?

**Comment by wuhan321** [comment]
> > 我也安装了python@3.10,,,还是打不开,请教下怎么回事
> 
> 正式版用的python 3.10，Nightly用的3.11. Win用的3.9.

已经解决，谢谢
