### ISSUE TITLE
后面会支持M1的版本吗

### ISSUE THREAD

**Issue by zyzyzy523** [FuckDoctors/rdm-builder#30]
M1芯片的打不开

**Comment by augustdai** [comment]
同问。什么时候能推出M2芯片版本的

**Comment by FuckDoctors** [comment]
暂时不支持，Github Action支持M1的时候再考虑。

**Comment by FuckDoctors** [comment]
可以看看 #26 里的说明。

**Comment by zyzyzy523** [comment]
> 同问。什么时候能推出M2芯片版本的

https://github.com/kanyways/rdm 这里有M2的版本下载
