### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by li395092734** [FuckDoctors/rdm-builder#32]
原因我知道是缺少指定版本的Python，但是发现这个报错不是个例呀。必须要指定版本的Python才能安装成功。这个是不是有点问题呢。是不是可以优化一下呢、

<img width="260" alt="1111" src="https://user-images.githubusercontent.com/50952020/226782846-588906ef-eefb-43c6-91fd-ae1f6f735929.png">

**Comment by FuckDoctors** [comment]
#34 集成了python了，回头试试看
