### ISSUE TITLE
打开编译好的版本没有任何提示

### ISSUE THREAD

**Issue by wuhan321** [FuckDoctors/rdm-builder#6]
允许安装一切来源了,打开无任何提示

**Comment by FuckDoctors** [comment]
估计是Python版本的问题，你看下这个issue https://github.com/FuckDoctors/rdm-builder/issues/2

**Comment by wuhan321** [comment]
https://github.com/FuckDoctors/rdm-builder/issues/2#issuecomment-706037933 已解决
