### ISSUE TITLE
CoreFoundation 和 CoreServices

### ISSUE THREAD

**Issue by CCint3** [FuckDoctors/rdm-builder#7]
```
clang: error: no such file or directory: '/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation'
clang: error: no such file or directory: '/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices'
```

这个错误怎么处理呢？

**Comment by FuckDoctors** [comment]
最近没在macOS上用了，没见到这个错误。
看起来是系统级的问题啊。。
装XCode Command Line Tools了吗

**Comment by FuckDoctors** [comment]
这个是macOS 11.0上的问题，uglide已经修复了。
https://github.com/uglide/RedisDesktopManager/pull/4950
可以使用[pre-release](https://github.com/FuckDoctors/rdm-builder/releases/tag/2020-nightly)版。
