### ISSUE TITLE
您好，我是github上vue-activiti-demo工作流仓库的创建人，由于项目中涉及公司信息，现公司要求删除，麻烦您将您fork的这个仓库删除，非常感谢，祝您工作愉快。

### ISSUE THREAD

**Issue by griabcrh** [FuckDoctors/rdm-builder#9]
您好，我是github上vue-activiti-demo工作流仓库的创建人，由于项目中涉及公司信息，现公司要求删除，麻烦您将您fork的这个仓库删除，非常感谢，祝您工作愉快。

**Comment by FuckDoctors** [comment]
您好，感谢您的文章和代码，对了解activiti有很大帮助，fork的仓库已删除。
期待有更好的作品！也祝您工作愉快~
